/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package btl_qlns;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author NGUYEN THI GIANG
 */
public class QuanLyKhachHang extends javax.swing.JInternalFrame {

    private KetNoi ketNoi = new KetNoi();

    /**
     * Creates new form QuanLyKhachHang
     */
    public QuanLyKhachHang() {
        initComponents();
        Calendar calendar = Calendar.getInstance();
        Date currentDate = calendar.getTime();
        txtNgaySinh.setDate(currentDate);
        loadData("SELECT makh, hoten, cmnd, ngaysinh, diachi, sdt, mucdich, thanhtoan FROM khachhang ");
    }

    private void loadData(String query) {
        DefaultTableModel model = (DefaultTableModel) tbDSKH.getModel();
        model.setRowCount(0);
        tbDSKH.setAutoCreateRowSorter(true);
        ResultSet rs = ketNoi.executeQuery(query);

        try {
            while (rs.next()) {
                String maKH = rs.getString(1);
                String hoTen = rs.getString(2);
                String cmnd = rs.getString(3);
                String ngaySinh = rs.getString(4);
                String diaChi = rs.getString(5);
                String sdt = rs.getString(6);
                String mucDich = rs.getString(7);
                boolean thanhToan = rs.getBoolean(8);  // Assuming that the 8th column is the boolean column (thanhtoan)

                // Create an array with the data
                Object[] rowData = {maKH, hoTen, cmnd, ngaySinh, diaChi, sdt, mucDich, thanhToan};

                // Add the row to the model
                model.addRow(rowData);
            }
        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(null, "Lỗi: " + ex.getMessage(), "Thông báo", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btXoaKH = new javax.swing.JButton();
        btInKH = new javax.swing.JButton();
        btTimKiemKH = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbDSKH = new javax.swing.JTable();
        txtTimKiemKH = new javax.swing.JTextField();
        btHienThiChuaThanhToan = new javax.swing.JButton();
        btHienThiDaThanhToan = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        txtHoTenKH = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDiaChiKH = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtSDTKH = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtCMND = new javax.swing.JTextField();
        txtNgaySinh = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        txtMucDichKH = new javax.swing.JTextField();
        btn_Update = new javax.swing.JButton();
        btnreLoad = new javax.swing.JButton();
        btSuaKH = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btXoaKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btXoaKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/file.png"))); // NOI18N
        btXoaKH.setText("Xoá khách hàng");
        btXoaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaKHActionPerformed(evt);
            }
        });

        btInKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btInKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/printer.png"))); // NOI18N
        btInKH.setText("In danh sách");
        btInKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInKHActionPerformed(evt);
            }
        });

        btTimKiemKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btTimKiemKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/loupe.png"))); // NOI18N
        btTimKiemKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btTimKiemKHMouseClicked(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setText("Tìm kiếm theo tên:");

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        tbDSKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null,  new Boolean(false)},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã khách hàng", "Tên khách hàng", "CMND", "Ngày sinh", "Địa chỉ", "Số điện thoại", "Mục đích", "Thanh toán"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbDSKH.setColumnSelectionAllowed(true);
        tbDSKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDSKHMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbDSKH);
        tbDSKH.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        txtTimKiemKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTimKiemKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemKHActionPerformed(evt);
            }
        });

        btHienThiChuaThanhToan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btHienThiChuaThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/task.png"))); // NOI18N
        btHienThiChuaThanhToan.setText("Hiển thị khách hàng chưa thanh toán");
        btHienThiChuaThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHienThiChuaThanhToanActionPerformed(evt);
            }
        });

        btHienThiDaThanhToan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btHienThiDaThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/to-do-list.png"))); // NOI18N
        btHienThiDaThanhToan.setText("Hiển thị khách hàng đã thanh toán");
        btHienThiDaThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHienThiDaThanhToanActionPerformed(evt);
            }
        });

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel6.setText("Ngày sinh:");

        jLabel9.setText("Địa chỉ:");

        jLabel10.setText("Số điện thoại:");

        jLabel11.setText("Mục đích sử dụng:");

        jLabel5.setText("Họ và tên:");

        jLabel34.setText("CMT/CCCD:");

        jLabel1.setText("Mã khách hàng");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(25, 25, 25)
                        .addComponent(txtMucDichKH))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel34)
                            .addComponent(jLabel1))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSDTKH)
                            .addComponent(txtDiaChiKH)
                            .addComponent(txtHoTenKH)
                            .addComponent(txtCMND)
                            .addComponent(txtNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMaKH))))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(txtDiaChiKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txtSDTKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtMucDichKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        btn_Update.setText("Cập nhật");
        btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateActionPerformed(evt);
            }
        });

        btnreLoad.setText("ReLoad");
        btnreLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreLoadActionPerformed(evt);
            }
        });

        btSuaKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btSuaKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit-text.png"))); // NOI18N
        btSuaKH.setText("Sửa khách hàng");
        btSuaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaKHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTimKiemKH, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btTimKiemKH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btHienThiChuaThanhToan)
                            .addComponent(btHienThiDaThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btInKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btXoaKH, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btSuaKH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(btn_Update)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnreLoad))))
                                .addGap(57, 57, 57)))
                        .addGap(23, 23, 23)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btTimKiemKH, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel28)
                        .addComponent(txtTimKiemKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btHienThiDaThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btHienThiChuaThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Update)
                            .addComponent(btnreLoad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSuaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btXoaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btInKH, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbDSKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDSKHMouseClicked
        int row = tbDSKH.getSelectedRow();
        if (row >= 0) {
            DefaultTableModel model = (DefaultTableModel) tbDSKH.getModel();
            txtMaKH.setText(model.getValueAt(row, 0).toString());
            txtHoTenKH.setText(model.getValueAt(row, 1).toString());
            txtCMND.setText(model.getValueAt(row, 2).toString());
            try {
                txtNgaySinh.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(row, 3).toString()));
            } catch (ParseException ex) {
                Logger.getLogger(QuanLyHopDong.class.getName()).log(Level.SEVERE, null, ex);
            }
            txtDiaChiKH.setText(model.getValueAt(row, 4).toString());
            txtSDTKH.setText(model.getValueAt(row, 5).toString());
            txtMucDichKH.setText(model.getValueAt(row, 6).toString());
        }
    }//GEN-LAST:event_tbDSKHMouseClicked

    private void btTimKiemKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btTimKiemKHMouseClicked
        String searchKeyword = txtTimKiemKH.getText().trim();

        // Check if the search keyword is not empty
        if (!searchKeyword.isEmpty()) {
            // Load data with the search query
            loadData("SELECT makh, hoten, cmnd, ngaysinh, diachi, sdt, mucdich FROM khachhang WHERE hoten LIKE '%" + searchKeyword + "%'");
        } else {
            // If the search keyword is empty, reload all data
            loadData("SELECT makh, hoten, cmnd, ngaysinh, diachi, sdt, mucdich FROM khachhang");
        }
    }//GEN-LAST:event_btTimKiemKHMouseClicked

    private void txtTimKiemKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemKHActionPerformed

    private void btXoaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaKHActionPerformed

        int rowIndex = tbDSKH.getSelectedRow();

        if (rowIndex >= 0) {
            String maKH = tbDSKH.getValueAt(rowIndex, 0).toString();

            DefaultTableModel model = (DefaultTableModel) tbDSKH.getModel();
            model.removeRow(rowIndex);

            String deleteQuery = "DELETE FROM khachhang WHERE makh = '" + maKH + "'";

            int result = ketNoi.executeUpdate(deleteQuery);

            if (result > 0) {
                JOptionPane.showMessageDialog(null, "Xóa khách hàng thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Xóa khách hàng thất bại.", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn một khách hàng để xóa.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btXoaKHActionPerformed

    private void btInKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInKHActionPerformed
        try {
            XSSFWorkbook wordkbook = new XSSFWorkbook();
            XSSFSheet sheet = wordkbook.createSheet("khachhang");
            XSSFRow row = null;
            Cell cell = null;
            row = sheet.createRow(2);
            cell = row.createCell(0, CellType.STRING);
            cell.setCellValue("Danh sách khách hàng");

            row = sheet.createRow(3);
            cell = row.createCell(0, CellType.STRING);
            cell.setCellValue("STT");

            cell = row.createCell(1, CellType.STRING);
            cell.setCellValue("Mã khách hàng");

            cell = row.createCell(2, CellType.STRING);
            cell.setCellValue("Tên khách hàng");

            cell = row.createCell(3, CellType.STRING);
            cell.setCellValue("CMND");

            cell = row.createCell(4, CellType.STRING);
            cell.setCellValue("Ngày sinh");

            cell = row.createCell(5, CellType.STRING);
            cell.setCellValue("Địa chỉ");

            cell = row.createCell(6, CellType.STRING);
            cell.setCellValue("Số điện thoại");

            cell = row.createCell(7, CellType.STRING);
            cell.setCellValue("Mục đích");

            for (int i = 0; i < tbDSKH.getRowCount(); i++) {
                //Modelbook book =arr.get(i);
                row = sheet.createRow(4 + i);

                cell = row.createCell(0, CellType.NUMERIC);
                cell.setCellValue(i + 1);

                cell = row.createCell(1, CellType.STRING);
                cell.setCellValue(tbDSKH.getModel().getValueAt(i, 0).toString());

                cell = row.createCell(2, CellType.STRING);
                cell.setCellValue(tbDSKH.getModel().getValueAt(i, 1).toString());

                cell = row.createCell(3, CellType.STRING);
                cell.setCellValue(tbDSKH.getModel().getValueAt(i, 2).toString());

                cell = row.createCell(4, CellType.STRING);
                cell.setCellValue(tbDSKH.getModel().getValueAt(i, 3).toString());

                cell = row.createCell(5, CellType.STRING);
                cell.setCellValue(tbDSKH.getModel().getValueAt(i, 4).toString());

                cell = row.createCell(6, CellType.STRING);
                cell.setCellValue(tbDSKH.getModel().getValueAt(i, 5).toString());

                cell = row.createCell(7, CellType.STRING);
                cell.setCellValue(tbDSKH.getModel().getValueAt(i, 6).toString());
            }

            // Tạo một đối tượng JFileChooser
            JFileChooser fileChooser = new JFileChooser();

            // Tạo một bộ lọc cho phép chỉ chọn các file có đuôi là .xlsx
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Excel Files (*.xlsx)", "xlsx");
            fileChooser.setFileFilter(filter);

            // Hiển thị hộp thoại chọn file, và kiểm tra xem người dùng có chọn một file hay không
            int result = fileChooser.showSaveDialog(null);

            if (result == JFileChooser.APPROVE_OPTION) {
                // Lấy đường dẫn file được chọn
                File selectedFile = fileChooser.getSelectedFile();

                try {
                    FileOutputStream fis = new FileOutputStream(selectedFile + ".xlsx");
                    wordkbook.write(fis);
                    fis.close();

                    JOptionPane.showMessageDialog(null, "In thành công tại: " + selectedFile.getAbsolutePath());
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Loi mo file");
        }
    }//GEN-LAST:event_btInKHActionPerformed

    private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateActionPerformed
        // TODO add your handling code here:
        // Iterate through JTable rows
        int successCount = 0;
        DefaultTableModel model = (DefaultTableModel) tbDSKH.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            String maKH = model.getValueAt(i, 0).toString();
            String hoTen = model.getValueAt(i, 1).toString();
            String cmnd = model.getValueAt(i, 2).toString();
            String ngaySinh = model.getValueAt(i, 3).toString();
            String diaChi = model.getValueAt(i, 4).toString();
            String sdt = model.getValueAt(i, 5).toString();
            String mucDich = model.getValueAt(i, 6).toString();
            Boolean thanhToanValue = (Boolean) model.getValueAt(i, 7);
            boolean thanhToan = (thanhToanValue != null && thanhToanValue);

            // Update the database based on the retrieved values
            String updateQuery = "UPDATE khachhang SET "
                    + "hoten = '" + hoTen + "', "
                    + "cmnd = '" + cmnd + "', "
                    + "ngaysinh = '" + ngaySinh + "', "
                    + "diachi = '" + diaChi + "', "
                    + "sdt = '" + sdt + "', "
                    + "mucdich = '" + mucDich + "', "
                    + "thanhtoan = " + (thanhToan ? 1 : 0) + " " // Assuming 1 represents true and 0 represents false
                    + "WHERE makh = '" + maKH + "'";

            int result = ketNoi.executeUpdate(updateQuery);
            if (result > 0) {
                successCount++;
            }
        }
        if (successCount == model.getRowCount()) {
            JOptionPane.showMessageDialog(null, "Cập nhật thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Cập nhật thất bại", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_UpdateActionPerformed

    private void btHienThiDaThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHienThiDaThanhToanActionPerformed
        // TODO add your handling code here:
        String query = "SELECT makh, hoten, cmnd, ngaysinh, diachi, sdt, mucdich, thanhtoan FROM khachhang WHERE thanhtoan = 1";
        loadData(query);
    }//GEN-LAST:event_btHienThiDaThanhToanActionPerformed

    private void btnreLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreLoadActionPerformed
        // TODO add your handling code here:
        loadData("SELECT makh, hoten, cmnd, ngaysinh, diachi, sdt, mucdich, thanhtoan FROM khachhang ");
    }//GEN-LAST:event_btnreLoadActionPerformed

    private void btHienThiChuaThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHienThiChuaThanhToanActionPerformed
        // TODO add your handling code here:
        String query = "SELECT makh, hoten, cmnd, ngaysinh, diachi, sdt, mucdich, thanhtoan FROM khachhang WHERE thanhtoan = 0";
        loadData(query);

    }//GEN-LAST:event_btHienThiChuaThanhToanActionPerformed

    private void btSuaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaKHActionPerformed
        if (txtMaKH.getText().equals("") || txtHoTenKH.getText().equals("") || txtCMND.getText().equals("") || txtDiaChiKH.getText().equals("") || txtSDTKH.getText().equals("") || txtMucDichKH.getText().equals("")) {
            JOptionPane.showConfirmDialog(null, "Các trường nhập không được để trống!", "Thông báo", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        try {
        String maKH = txtMaKH.getText();
        ResultSet existingCustomer = ketNoi.executeQuery("SELECT * FROM khachhang WHERE makh = '" + maKH + "';");

        if (!existingCustomer.next()) {
            JOptionPane.showMessageDialog(null, "Mã khách hàng không tồn tại! Mời bạn nhập mã khách hàng khác", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            DefaultTableModel model = (DefaultTableModel) tbDSKH.getModel();
            int selectedRow = tbDSKH.getSelectedRow();
            
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(null, "Vui lòng chọn một khách hàng từ bảng để sửa thông tin.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            
            Boolean thanhToanValue = (Boolean) model.getValueAt(selectedRow, 7); // Assuming 6 is the column index for thanhToan
            boolean thanhToan = thanhToanValue != null && thanhToanValue;

            String updateQuery = "UPDATE khachhang SET "
                    + "hoten = '" + txtHoTenKH.getText() + "', "
                    + "ngaysinh = '" + new SimpleDateFormat("yyyy-MM-dd").format(txtNgaySinh.getDate()) + "', "
                    + "diachi = '" + txtDiaChiKH.getText() + "', "
                    + "sdt = '" + txtSDTKH.getText() + "', "
                    + "mucdich = '" + txtMucDichKH.getText() + "', "
                    + "cmnd = '" + txtCMND.getText() + "', "
                    + "thanhToan = " + (thanhToan ? 1 : 0) + " "
                    + "WHERE makh = '" + maKH + "';";

            ketNoi.executeUpdate(updateQuery);

            // Clear the text fields after successful update
            txtMaKH.setText("");
            txtHoTenKH.setText("");
            txtCMND.setText("");
            txtDiaChiKH.setText("");
            txtSDTKH.setText("");
            txtMucDichKH.setText("");

            // Reload the data in the table
            loadData("SELECT makh, hoten, cmnd, ngaysinh, diachi, sdt, mucdich, thanhtoan FROM khachhang;");
            
            int result = ketNoi.executeUpdate(updateQuery);

            if (result > 0) {
                JOptionPane.showMessageDialog(null, "Sửa khách hàng thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Sửa khách hàng thất bại.", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Lỗi: " + ex.getMessage(), "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btSuaKHActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btHienThiChuaThanhToan;
    private javax.swing.JButton btHienThiDaThanhToan;
    private javax.swing.JButton btInKH;
    private javax.swing.JButton btSuaKH;
    private javax.swing.JButton btTimKiemKH;
    private javax.swing.JButton btXoaKH;
    private javax.swing.JButton btn_Update;
    private javax.swing.JButton btnreLoad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbDSKH;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtDiaChiKH;
    private javax.swing.JTextField txtHoTenKH;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtMucDichKH;
    private com.toedter.calendar.JDateChooser txtNgaySinh;
    private javax.swing.JTextField txtSDTKH;
    private javax.swing.JTextField txtTimKiemKH;
    // End of variables declaration//GEN-END:variables
}
